version: "3"

services: 
    mysql:
        image: mysql:5.7.21
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=root
            - MYSQL_DATABASE=football
        ports:
            - 3307:3306
        volumes:
            - ./data/mysql/:/var/lib/mysql
        networks:
            - mysql

    footballapp:
        container_name: footballapp
        build: ./db
        depends_on:
            - mysql
        environment:
            - MYSQL_HOST=mysql
            - MYSQL_DATABASE=football
            - MYSQL_USERNAME=root
            - MYSQL_PORT=3306
        ports:
            - 8000:80
        networks:
            - mysql
            - api

    fe:
        container_name: fe
        build: ./fe
        ports:
            - 88:3000
        stdin_open: true
        environment:
            - REACT_APP_SERVER_URL=http://footballapp:8000
        networks:
            - api

networks:
    api:
    mysql:
